version: '3'

services:
  # Server / API - Node JS
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

#  # Web client - React
#  web:
#    restart: always
#    build:
#      context: ./web
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - server